### ISSUE TITLE
Massive REST API log spam if Coupons post type is disabled

### ISSUE THREAD

**Issue by lkraav** [metorikhq/metorik-helper#106]
It's the capability checks on a non-existent post type.

Here's what happens https://sentry.io/share/issue/5ed4a1cf7aa646aebf2624be62cbb3a9/

To reproduce

* go to /wp-admin/admin.php?page=wc-settings
* uncheck "Enable the use of coupon codes"

**Comment by bryceadams** [comment]
Great catch @lkraav, thank you! I'll get this fixed up in the next release too (hopefully there will be one in December or so, just waiting until I can get a bunch of issues fixed at once for it).

**Comment by bryceadams** [comment]
The only way to solve this issue is to stop coupon-related API requests on our end. Will add a measure on our side to stop these requests if a store has no coupons :)
