### ISSUE TITLE
Frontend CSS

### ISSUE THREAD

**Issue by daviddarke** [metorikhq/metorik-helper#82]
Hi there, quick question. We are running some site optimisations for a client and a CSS file from Metorik is appearing on the frontend:

<img width="844" alt="Screen Shot 2019-05-28 at 14 29 56" src="https://user-images.githubusercontent.com/1636310/58481980-68163580-8155-11e9-9bf3-6953c5b1a58f.png">

1. What purpose does that serve from a frontend perspective?
1. Can I just de_enqueue from the frontend without breaking anything? 
   1. Or even could the style and js call be wrapped in an `is_admin()`

**Comment by daviddarke** [comment]
Oh to add, the results above are from Google Pagespeed insights: https://developers.google.com/speed/pagespeed/insights/. So this represents a logged out user.

**Comment by bryceadams** [comment]
Hi @daviddarke! The CSS added by that file is just for the 'add to cart popup' feature I believe and a few other cart-related UI stuff. So feel free to try dequeue it if you aren't using that feature / don't need it.

​Any issues, please let me know. :)

**Comment by daviddarke** [comment]
Thanks
