### ISSUE TITLE
Performance: metorik.js

### ISSUE THREAD

**Issue by BusinessBloomer** [metorikhq/metorik-helper#89]
Hi Bryce. Does this script need to run on non-WC pages? 

It would be great if you could dequeue when it's not needed in order to optimize performance

**Comment by bryceadams** [comment]
It shouldn't make a different at that point as it's been cached. But in general we need to run it as it has other code for tracking session pages, counts, etc. You could technically do this yourself though. See the code at the bottom here: https://help.metorik.com/article/76-about-source-tracking - just check for the page type / content before dequeueing.

**Comment by BusinessBloomer** [comment]
Wow awesome
